server.port=${PORT:8080}
spring.application.name=student

# MongoDB (taken from environment variable)
spring.data.mongodb.uri=${MONGO_URI}

# JWT Configuration
jwt.secret=MySecretKeyForJWTSigning12345678901234567890