server.port=${PORT:8080}
spring.application.name=student

# MongoDB (taken from environment variable)
spring.data.mongodb.uri=mongodb+srv://sankavi2410743_db_user:Murugan123@cluster0.lvhyybu.mongodb.net/studentdb?retryWrites=true&w=majority

# JWT Configuration
jwt.secret=MySecretKeyForJWTSigning12345678901234567890